#!/bin/bash

# Output colors
NORMAL="\\033[0;39m"
RED="\\033[1;31m"
BLUE="\\033[1;34m"

drone-build() {
  npm config set loglevel warn
  npm install --quiet
  bower install --allow-root --quiet
  bower --force update --allow-root --quiet
  ember build --environment production
}

clr() {
  rm -rf ./tmp
  rm -rf ./if-you-need-to-delete-this-open-an-issue-async-disk-cache
}

start() {
  ember server --watcher polling --environment development
  clr
}

setup() {
  npm install
  bower install --allow-root
  bower --force update --allow-root
}

build() {
  ember build --environment production
  clr
}

build-full() {
  setup
  ember build --environment production
  clr
}

dev() {
  rm -rf /app/node_modules/yebo-ember-auth
  rm -rf /app/node_modules/yebo-ember-checkouts
  rm -rf /app/node_modules/yebo-ember-core
  rm -rf /app/node_modules/yebo-ember-storefront
  rm -rf /app/bower_components/yebo_sdk
  ln -sf /packages/node_modules/* /app/node_modules
  ln -sf /packages/bower_components/* /app/bower_components
}

help() {
  echo "-----------------------------------------------------------------------"
  echo "                      Available commands                              -"
  echo "-----------------------------------------------------------------------"
  echo -e -n "$BLUE"
  echo "   > start - Start ember without symbolic links"
  echo "   > build - Run build script"
  echo "   > build-full - Run build script and fetch dependencies"
  echo "   > setup - Install dependencies"
  echo "   > help - Display this help"
  echo -e -n "$NORMAL"
  echo "-----------------------------------------------------------------------"
}

$*
