#!/bin/bash

# Output colors
NORMAL="\\033[0;39m"
RED="\\033[1;31m"
BLUE="\\033[1;34m"

clr() {
  rm -rf ./tmp
}

cache() {
  npm config set registry http://127.0.0.1:8080/
}

setup() {
  npm install
  bower install --allow-root
  bower --force update --allow-root
}

up() {
  ember server --watcher polling
  clr
}

build-full() {
  setup
  ember build --environment production
  clr
}

build-dev() {
  setup
  dev
  ember build --environment production
  clr
}

build() {
  ember build --environment production
  clr
}

dev() {
  rm -rf /usr/src/app/node_modules/yebo-ember-auth
  rm -rf /usr/src/app/node_modules/yebo-ember-checkouts
  rm -rf /usr/src/app/node_modules/yebo-ember-core
  rm -rf /usr/src/app/node_modules/yebo-ember-storefront
  rm -rf /usr/src/app/bower_components/yebo_sdk
  ln -sf /packages/node_modules/* /usr/src/app/node_modules
  ln -sf /packages/bower_components/* /usr/src/app/bower_components
}

help() {
  echo "-----------------------------------------------------------------------"
  echo "                      Available commands                              -"
  echo "-----------------------------------------------------------------------"
  echo -e -n "$BLUE"
  echo "   > up - Start ember without symbolic links"
  echo "   > build - Run build script"
  echo "   > build-full - Run build script and fetch dependencies"
  echo "   > dev - Start ember server with symbolic links"
  echo "   > clr - Remove tmp folder"
  echo "   > setup - Install dependencies"
  echo "   > cache - Set cache in npm"
  echo "   > help - Display this help"
  echo -e -n "$NORMAL"
  echo "-----------------------------------------------------------------------"
}

$*
